# Finnish translations for PROJECT.
# Copyright (C) 2024 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2024.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2024-02-19 22:26+0200\n"
"PO-Revision-Date: 2024-02-19 22:17+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: fi\n"
"Language-Team: fi <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.13.0\n"

#: core/config.py:95
msgid "Debug"
msgstr ""

#: core/config.py:96
msgid "Info"
msgstr ""

#: core/config.py:97
msgid "Warn"
msgstr ""

#: core/config.py:98
msgid "Error"
msgstr ""

#: core/config.py:106
msgid "Base url of the application"
msgstr ""

#: core/config.py:112
msgid "Log Level"
msgstr ""

#: core/config.py:119
msgid "Application name"
msgstr ""

#: core/config.py:120
msgid ""
"Log messages originating from this application will be tagged with this "
"name. If you run multiple instances, giving each one a different "
"application name will help you determine which instance is having "
"problems."
msgstr ""

#: core/config.py:128
msgid "Database Log Level"
msgstr ""

#: core/config.py:131
msgid ""
"Database logs are extremely verbose, so unless you're diagnosing a "
"database-related problem, it's a good idea to set a higher log level for "
"database messages."
msgstr ""

#: core/config.py:138
msgid "Excluded audiobook sources"
msgstr ""

#: core/config.py:139
msgid ""
"Audiobooks from these data sources will be hidden from the collection, "
"even if they would otherwise show up as available."
msgstr ""

#: core/config.py:147
msgid "Cleanup old measurement data"
msgstr ""

#: core/config.py:149
msgid ""
"If this settings is 'true' old book measurement data will be cleaned out "
"of the database. Some sites may want to keep this data for later "
"analysis."
msgstr ""

#: core/config.py:157
msgid "Push notifications status"
msgstr ""

#: core/config.py:159
msgid ""
"If this settings is 'true' push notification jobs will run as scheduled, "
"and attempt to notify patrons via mobile push notifications."
msgstr ""

#: core/config.py:163
msgid "True"
msgstr ""

#: core/config.py:164
msgid "False"
msgstr ""

#: core/connection_config.py:17
msgid "Connection retry limit"
msgstr ""

#: core/connection_config.py:18
msgid ""
"The maximum number of times to retry a request for certain connection-"
"related errors."
msgstr ""

#: core/external_search.py:108 core/opds_import.py:110
msgid "URL"
msgstr ""

#: core/external_search.py:114
msgid "Index prefix"
msgstr ""

#: core/external_search.py:117
msgid ""
"Any Search indexes needed for this application will be created with this "
"unique prefix. In most cases, the default will work fine. You may need to"
" change this if you have multiple application servers using a single "
"Search server."
msgstr ""

#: core/external_search.py:123
msgid "Test search term"
msgstr ""

#: core/external_search.py:125
msgid "Self tests will use this value as the search term."
msgstr ""

#: core/external_search.py:2628
#, python-format
msgid "Invalid page key: %(key)s"
msgstr ""

#: core/facets.py:72
msgid "Sort by"
msgstr ""

#: core/facets.py:73
msgid "Availability"
msgstr ""

#: core/facets.py:74
msgid "Collection"
msgstr ""

#: core/facets.py:75
msgid "Distributor"
msgstr ""

#: core/facets.py:76
msgid "Collection Name"
msgstr ""

#: core/facets.py:80
msgid "Allow patrons to sort by"
msgstr ""

#: core/facets.py:81
msgid "Allow patrons to filter availability to"
msgstr ""

#: core/facets.py:82
msgid "Allow patrons to filter collection to"
msgstr ""

#: core/facets.py:83
msgid "Allow patrons to filter by distributor"
msgstr ""

#: core/facets.py:84
msgid "Allow patrons to filter by collection name"
msgstr ""

#: core/facets.py:90
msgid "Title"
msgstr ""

#: core/facets.py:91
msgid "Author"
msgstr ""

#: core/facets.py:92
msgid "Last Update"
msgstr ""

#: core/facets.py:93
msgid "Recently Added"
msgstr ""

#: core/facets.py:94
msgid "Series Position"
msgstr ""

#: core/facets.py:95
msgid "Work ID"
msgstr ""

#: core/facets.py:96
msgid "Available now"
msgstr ""

#: core/facets.py:97
msgid "All"
msgstr "Kaikki"

#: core/facets.py:98
msgid "Yours to keep"
msgstr ""

#: core/facets.py:99
msgid "Everything"
msgstr ""

#: core/facets.py:100
msgid "Popular Books"
msgstr ""

#: core/lane.py:380
#, python-format
msgid "I don't know how to order a feed by '%(order)s'"
msgstr ""

#: core/lane.py:388
#, python-format
msgid "I don't understand the availability term '%(availability)s'"
msgstr ""

#: core/lane.py:400
#, python-format
msgid "I don't understand what '%(collection)s' refers to."
msgstr ""

#: core/lane.py:416
#, python-format
msgid "I don't understand which distributor '%(distributor)s' refers to."
msgstr ""

#: core/lane.py:432
#, python-format
msgid "I don't understand which collection '%(collection_name)s' refers to."
msgstr ""

#: core/lane.py:1216
#, python-format
msgid "Invalid page size: %(size)s"
msgstr ""

#: core/lane.py:1234
#, python-format
msgid "Invalid offset: %(offset)s"
msgstr ""

#: core/lane.py:1555
#, python-format
msgid "All %(worklist)s"
msgstr ""

#: core/opds2_import.py:194 core/opds_import.py:166
msgid "Custom accept header"
msgstr ""

#: core/opds2_import.py:195 core/opds_import.py:168
msgid ""
"Some servers expect an accept header to decide which file to send. You "
"can use */* if the server doesn't expect anything."
msgstr ""

#: core/opds2_import.py:207
msgid "List of identifiers that will be skipped"
msgstr ""

#: core/opds2_import.py:208
msgid ""
"Circulation Manager will not be importing publications with identifiers "
"having one of the selected types."
msgstr ""

#: core/opds2_import.py:326
msgid "Import books from a publicly-accessible OPDS 2.0 feed."
msgstr ""

#: core/opds_import.py:116
msgid "Data source name"
msgstr ""

#: core/opds_import.py:122
msgid "Default audience"
msgstr ""

#: core/opds_import.py:123
msgid ""
"If the vendor does not specify the target audience for their books, "
"assume the books have this target audience."
msgstr ""

#: core/opds_import.py:129
msgid "No default audience"
msgstr ""

#: core/opds_import.py:138
msgid "Username"
msgstr ""

#: core/opds_import.py:139
msgid ""
"If HTTP Basic authentication is required to access the OPDS feed (it "
"usually isn't), enter the username here."
msgstr ""

#: core/opds_import.py:148
msgid "Password"
msgstr ""

#: core/opds_import.py:149
msgid ""
"If HTTP Basic authentication is required to access the OPDS feed (it "
"usually isn't), enter the password here."
msgstr ""

#: core/opds_import.py:177
msgid "Identifer"
msgstr ""

#: core/opds_import.py:179
msgid "Which book identifier to use as ID."
msgstr ""

#: core/opds_import.py:182
msgid "(Default) Use <id>"
msgstr ""

#: core/opds_import.py:183
msgid "Use <dcterms:identifier> first, if not exist use <id>"
msgstr ""

#: core/opds_import.py:654
msgid "Import books from a publicly-accessible OPDS feed."
msgstr ""

#: core/problem_details.py:11
msgid "Invalid input."
msgstr ""

#: core/problem_details.py:12
msgid "You provided invalid or unrecognized input."
msgstr ""

#: core/problem_details.py:18
msgid "Invalid credentials"
msgstr ""

#: core/problem_details.py:19
msgid "Valid credentials are required."
msgstr ""

#: core/problem_details.py:25
msgid "Method not allowed"
msgstr ""

#: core/problem_details.py:26
msgid "The HTTP method you used is not allowed on this resource."
msgstr ""

#: core/problem_details.py:32
msgid "Unsupported media type"
msgstr ""

#: core/problem_details.py:33
msgid "You submitted an unsupported media type."
msgstr ""

#: core/problem_details.py:39
msgid "Payload too large"
msgstr ""

#: core/problem_details.py:40
msgid "You submitted a document that was too large."
msgstr ""

#: core/problem_details.py:46
msgid "Internal server error."
msgstr ""

#: core/problem_details.py:47
msgid "Internal server error"
msgstr ""

#: core/problem_details.py:56
msgid "Invalid URN"
msgstr ""

#: core/problem_details.py:57
msgid "Could not parse identifier."
msgstr ""

#: core/problem_details.py:63
msgid "Unrecognized data source."
msgstr ""

#: core/problem_details.py:64
msgid "I don't know anything about that data source."
msgstr ""

#: core/problem_details.py:70
msgid "Third-party service failed."
msgstr ""

#: core/problem_details.py:71
msgid "A third-party service has failed."
msgstr ""

#: core/problem_details.py:77
msgid "Invalid reset password token"
msgstr ""

#: core/problem_details.py:78
msgid "Provided reset password token is not valid."
msgstr ""

#: core/user_profile.py:41
#, python-format
msgid "Profile document is not a JSON object: %r."
msgstr ""

#: core/user_profile.py:47
#, python-format
msgid "Could not convert profile document to JSON: %r."
msgstr ""

#: core/user_profile.py:62
#, python-format
msgid "Expected %s"
msgstr ""

#: core/user_profile.py:67
msgid "Submitted profile document was not valid JSON."
msgstr ""

#: core/user_profile.py:71
msgid "Submitted profile document was not a JSON object."
msgstr ""

#: core/user_profile.py:83
#, python-format
msgid "\"%s\" is not a writable setting."
msgstr ""

#: core/util/http.py:27
msgid "Failure contacting external service"
msgstr ""

#: core/util/http.py:28
#, python-format
msgid ""
"The server tried to access %(service)s but the third-party service "
"experienced an error."
msgstr ""

#: core/util/http.py:75
msgid "Bad response"
msgstr ""

#: core/util/http.py:76
#, python-format
msgid ""
"The server made a request to %(service)s, and got an unexpected or "
"invalid response."
msgstr ""

#: core/util/http.py:148
msgid "Network failure contacting third-party service"
msgstr ""

#: core/util/http.py:149
#, python-format
msgid "The server experienced a network error while contacting %(service)s."
msgstr ""

#: core/util/http.py:158
msgid "Timeout"
msgstr ""

#: core/util/http.py:159
#, python-format
msgid "The server made a request to %(service)s, and that request timed out."
msgstr ""

